# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package FiftyOneDegrees::TrieV3;
use base qw(Exporter);
use base qw(DynaLoader);
package FiftyOneDegrees::TrieV3c;
bootstrap FiftyOneDegrees::TrieV3;
package FiftyOneDegrees::TrieV3;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package FiftyOneDegrees::TrieV3;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package FiftyOneDegrees::TrieV3;

*init = *FiftyOneDegrees::TrieV3c::init;
*getDeviceOffset = *FiftyOneDegrees::TrieV3c::getDeviceOffset;
*getPropertyIndex = *FiftyOneDegrees::TrieV3c::getPropertyIndex;
*getValue = *FiftyOneDegrees::TrieV3c::getValue;
*destroy = *FiftyOneDegrees::TrieV3c::destroy;
*processDeviceCSV = *FiftyOneDegrees::TrieV3c::processDeviceCSV;
*processDeviceJSON = *FiftyOneDegrees::TrieV3c::processDeviceJSON;
*dataSetInitWithPropertyString = *FiftyOneDegrees::TrieV3c::dataSetInitWithPropertyString;
*getMatch = *FiftyOneDegrees::TrieV3c::getMatch;

# ------- VARIABLE STUBS --------

package FiftyOneDegrees::TrieV3;

*DATA_SET_INIT_STATUS_SUCCESS = *FiftyOneDegrees::TrieV3c::DATA_SET_INIT_STATUS_SUCCESS;
*DATA_SET_INIT_STATUS_INSUFFICIENT_MEMORY = *FiftyOneDegrees::TrieV3c::DATA_SET_INIT_STATUS_INSUFFICIENT_MEMORY;
*DATA_SET_INIT_STATUS_CORRUPT_DATA = *FiftyOneDegrees::TrieV3c::DATA_SET_INIT_STATUS_CORRUPT_DATA;
*DATA_SET_INIT_STATUS_INCORRECT_VERSION = *FiftyOneDegrees::TrieV3c::DATA_SET_INIT_STATUS_INCORRECT_VERSION;
*DATA_SET_INIT_STATUS_FILE_NOT_FOUND = *FiftyOneDegrees::TrieV3c::DATA_SET_INIT_STATUS_FILE_NOT_FOUND;
1;
